import TheFooter from '@/components/TheFooter';
import TheHeader from '@/components/TheHeader';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import style from './layout.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <main className={style.main}>
          <div className={style.main__container}>
            {children}
          </div>
        </main>
        <TheFooter />
      </body>
    </html>
  )
}
